project:
  type: book
  output-dir: docs #docs _book

book:
  title: "Temas Selectos de Aprendizaje de Máquina"
  site-url: https://github.com/CursosENESJuriquilla/TS_Aprendizaje_de_Maquina_2027-1
  page-footer:  "Temas Selectos de ML, 7mo semestre: Haydeé Peruyero" 
  sidebar: 
    # background: "#ffcccc"
    logo: "figures/LogoENES.png" # Logo ENES
    search: true
  author: 
    - name: Haydeé Peruyero
      degrees: PhD
      url: https://haydeeperuyero.github.io/ 
      email: haydeeperuyero@unam.cmx
      affiliations:
        - name: ENES, Juriquilla - UNAM
          country: Mexico
          url: https://www.enesjuriquilla.unam.mx/
  
  date: "08/17/2026"
  page-navigation: true        # Provide next and previous article links in footer
  back-to-top-navigation: true # Provide a ‘back to top’ navigation button
  chapters:
    - index.qmd
    - temario.qmd
    - part: "**Introducción al Aprendizaje Automático**"
      chapters: 
          - parte1.qmd
    - part: "**Modelos no lineales**"
      chapters:
          - parte2.qmd # regresión polinomial
          - parte3.qmd
          - parte4.qmd
          - parte5.qmd
          - parte6.qmd
          - parte7.qmd
    - part: "**Métodos de ensamble y optimización de modelos**"
      chapters:
          - parte9.qmd
    - part: "**Máquinas de Soporte Vectorial**"
      chapters:
          - parte9.qmd
    - part: "**Aprendizaje no supervisado**"
      chapters:
          - parte9.qmd
    - part: "**Interpretabilidad y explicabilidad de modelos**"
      chapters:
          - parte9.qmd  
    
  # Information
  repo-url: https://github.com/CursosENESJuriquilla/TS_Aprendizaje_de_Maquina_2027-1 # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "figures/favicon.png" # icono de la pagina en pestana


format:
  html:
    crossrefs-hover: true
    footnotes-hover: true
    toc-depth: 4
    number-depth: 3
    # css
    css: styles.css
    linkcolor: "#007f99"
    
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      # dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    code-line-numbers: false #Numero de lineas
    code-annotations: hover #c(hover, below, select): posicion https://quarto.org/docs/authoring/code-annotation.html
    code-block-bg: true # Bloque de código
    code-block-border-left: "#007f99" # color del borde izquierdo del codigo
    syntax-highlighting: arrow # Estilo de los codigos https://quarto.org/docs/output-formats/html-code.html#highlighting
    freeze: false  # Desactivar congelamiento

editor: visual

bibliography: references.bib

lang: es

execute:
  error: true # Se aceptan errores
  message: false # Silenciar mensajes de salida
  echo: true

